// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuCbnEjCCmHVDxw76xlQq6Gu2joZjKVPI',
    appId: '1:666968649668:web:350ab22777d18713147e91',
    messagingSenderId: '666968649668',
    projectId: 'tagih-in-v2',
    authDomain: 'tagih-in-v2.firebaseapp.com',
    storageBucket: 'tagih-in-v2.firebasestorage.app',
    measurementId: 'G-58ZXMMC3SD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCPnCvQ6crZQFJUYK_CnzDsRsu5Afplk8',
    appId: '1:666968649668:android:727117febfadc327147e91',
    messagingSenderId: '666968649668',
    projectId: 'tagih-in-v2',
    storageBucket: 'tagih-in-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_W6erueXP-TDjoitEZAozj344W8Y-Czc',
    appId: '1:666968649668:ios:c535e11e59d0bef6147e91',
    messagingSenderId: '666968649668',
    projectId: 'tagih-in-v2',
    storageBucket: 'tagih-in-v2.firebasestorage.app',
    iosBundleId: 'com.example.tagihinV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_W6erueXP-TDjoitEZAozj344W8Y-Czc',
    appId: '1:666968649668:ios:c535e11e59d0bef6147e91',
    messagingSenderId: '666968649668',
    projectId: 'tagih-in-v2',
    storageBucket: 'tagih-in-v2.firebasestorage.app',
    iosBundleId: 'com.example.tagihinV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuCbnEjCCmHVDxw76xlQq6Gu2joZjKVPI',
    appId: '1:666968649668:web:67632b907860ac2b147e91',
    messagingSenderId: '666968649668',
    projectId: 'tagih-in-v2',
    authDomain: 'tagih-in-v2.firebaseapp.com',
    storageBucket: 'tagih-in-v2.firebasestorage.app',
    measurementId: 'G-8WL0NZVLTZ',
  );
}
